#!/bin/bash
set -ex

YTDLVERSION="$(git ls-remote --tags https://github.com/ytdl-org/youtube-dl.git | tail -n 2 | head -n 1 | awk -F '/' '{print $3}')"

TARGETS=()
TARGETS+=($YTDLVERSION)
TARGETS+=('latest')

for TARGET in "${TARGETS[@]}"; do
    docker push "$DOCKER_REPO:$TARGET"
done
