steps:
  setup-environments:
    image: busybox
    commands:
      - ARIA2VERSION=$(cat ./dependency-versions/aria2-latest.txt)
      - LIBWEBPVERSION=$(cat ./dependency-versions/libwebp-latest.txt)
      - YTDLPVERSION=$(cat ./dependency-versions/yt-dlp-latest.txt)
      - echo "ytdlp$YTDLPVERSION-aria2c$ARIA2VERSION-libwebp$LIBWEBPVERSION,latest" > .tags

  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      tags: ytdlp${YTDLPVERSION}-aria2c${ARIA2VERSION}-libwebp${LIBWEBPVERSION},latest
      repo: huanga/terrandin-video-downloader
      build_args_from_env: true
      platforms: linux/amd64
