steps:
  setup-environments:
    image: busybox
    commands:
      - ARIA2VERSION=$(cat ./dependency-versions/aria2-latest.txt)
      - LIBWEBPVERSION=$(cat ./dependency-versions/libwebp-latest.txt)
      - YTDLPVERSION=$(cat ./dependency-versions/yt-dlp-latest.txt)
      - echo "ytdlp$YTDLPVERSION-aria2c$ARIA2VERSION-libwebp$LIBWEBPVERSION,latest" > .tags
      - cat .tags

  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      tags: latest,ytdlp-$YTDLPVERSION
      repo: huanga/terrandin-video-downloader
      build_args_from_env: true
      platforms: linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
