---
steps:
  setup-environments:
    image: busybox
    commands:
      - ARIA2VERSION=$(cat ./dependency-versions/aria2-latest.txt)
      - LIBWEBPVERSION=$(cat ./dependency-versions/libwebp-latest.txt)
      - YTDLPVERSION=$(cat ./dependency-versions/yt-dlp-latest.txt)
      - TAG='ytdlp-'$(echo $YTDLPVERSION | sed 's/\.//g')'.libwebp-'$(echo $LIBWEBPVERSION | sed
        's/\.//g')'.aria2-'$(echo $ARIA2VERSION | sed 's/\.//g')
      - echo "$TAG" > .tags
      - echo "latest" >> .tags
      - cat .tags
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      build_args_from_env: true
      platforms: linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: huanga/terrandin-video-downloader
      tags_file: .tags
