steps:
  setup-environments:
    image: busybox
    commands:
      - ARIA2VERSION=$(cat ./dependency-versions/aria2-latest.txt)
      - LIBWEBPVERSION=$(cat ./dependency-versions/libwebp-latest.txt)
      - YTDLPVERSION=$(cat ./dependency-versions/yt-dlp-latest.txt)
      - TAG=$(echo $YTDLPVERSION | sed 's/\.//g')'.'$(echo $LIBWEBPVERSION | sed 's/\.//g')'.'$(echo $ARIA2VERSION | sed 's/\.//g')
      - echo "$TAG,latest" > .tags
      - cat .tags

  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      tags_file: .tags
      repo: huanga/terrandin-video-downloader
      build_args_from_env: true
      platforms: linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
